

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import {
  useGLTF,
  PerspectiveCamera,
  OrthographicCamera,
} from "@react-three/drei";

import contactModel from './model2.glb';

export function Contact3DModel(props) {

  const { nodes, materials } = useGLTF(contactModel);

  props.camera.cam = nodes.Camera;
 
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[4.718, 0, 0]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material.002"]}
        position={[1.072, 0, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <spotLight
        intensity={95.657}
        angle={Math.PI / 8}
        penumbra={0.15}
        decay={2}
        position={[2.754, 0.593, 0]}
        rotation={[-Math.PI / 2, 1.456, 0]}
      />
      <OrthographicCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        position={[1.597, 0, 0]}
        rotation={[0, Math.PI / 2, 0]}
      />
    </group>
  );
}

useGLTF.preload(contactModel);